import assert from "node:assert/strict";
import { closePool } from "../src/db/client.js";
import { getRawMemoryDb } from "../src/db/client-memory.js";
import { AutoAcceptVerificationRunner, verificationHoldCount } from "../src/services/auto-accept-verification-runner.js";
import { createAutoAcceptVerificationIntent, updateAutoAcceptVerificationResponse, listAutoAcceptVerificationJobs, claimAutoAcceptVerificationJob, reuseAutoAcceptVerificationEvidence } from "../src/repositories/auto-accept-verification-repository.js";
import { verifyAutoAcceptJob } from "../src/services/auto-accept-verifier.js";
import type { AutoAcceptVerificationJob, AutoAcceptVerificationOutcome } from "../src/services/auto-accept-verifier.js";
import type { ApiClient } from "../src/services/api-client.js";

const db = getRawMemoryDb();
const job = (teamId: number, traceId: string, requestIds = [101]): AutoAcceptVerificationJob => ({
  teamId, traceId, ruleId: `reuse-rule-${teamId}`, ruleName: "Reuse", bookingId: 900,
  requestIds, trips: requestIds.map(request_id => ({ request_id })), claimToken: 0,
  acceptResult: { ok: true, httpStatus: 200 }, acceptStartedAt: 1, acceptFinishedAt: 2,
  acceptRttMs: 1, ambiguousAccept: false, acceptAll: false,
});
const list = (status: number) => ({ retcode: 0, message: "", data: { pageno: 1, count: 1, total: 1,
  request_list: [{ request_id: 101, booking_id: 900, request_acceptance_status: status }] } });

async function enqueue(value: AutoAcceptVerificationJob) {
  db.prepare("INSERT OR IGNORE INTO notify_rules (id,team_id,name,need,auto_accept) VALUES (?,?,'Reuse',5,1)").run(value.ruleId, value.teamId);
  await createAutoAcceptVerificationIntent(value);
  await updateAutoAcceptVerificationResponse(value);
}

function worker(teamId: number, status: number | null, published: AutoAcceptVerificationOutcome[] = []) {
  let reads = 0;
  const runner = new AutoAcceptVerificationRunner(teamId, {
    fetchBookingRequestList: async () => { reads++; return status === null ? null : list(status); },
    acceptBookingRequests: async () => assert.fail("verification must never send another acceptance POST"),
  } as unknown as ApiClient, {
    canRun: () => true, onHold: () => {}, onSettled: () => {},
    publish: async outcome => { published.push(outcome); return true; },
  }, { retryDelayMs: 1, jitter: () => 0 });
  return { runner, reads: () => reads };
}

async function drain(runner: AutoAcceptVerificationRunner) {
  await runner.restore();
  await runner.runDue();
  await runner.idle();
}

function canonical(teamId: number, status: string, evidence: unknown, bookingId = 900) {
  db.prepare("INSERT INTO auto_accept_results (team_id,booking_id,request_id,status,reason_code,evidence_json) VALUES (?,?,101,?,?,?)")
    .run(teamId, bookingId, status, status === "owned" ? "verified_owned" : "verified_lost_race", JSON.stringify(evidence));
}

async function main() {
  // Two concurrent traces for one request must share the first proven result.
  // Removing booking serialization or pre-read reuse makes reads jump from 2 to 4.
  const successNotifications: AutoAcceptVerificationOutcome[] = [];
  await enqueue(job(201, "owned-a"));
  await enqueue(job(201, "owned-b"));
  const success = worker(201, 2, successNotifications);
  await drain(success.runner);
  assert.equal(success.reads(), 2, "duplicate traces should read the two provider tabs only once");
  assert.equal((await listAutoAcceptVerificationJobs(201)).length, 0);
  assert.equal(successNotifications.length, 1, "duplicate evidence must not repeat a success notification");
  assert.equal((db.prepare("SELECT need FROM notify_rules WHERE team_id=201").get() as { need: number }).need, 4);
  assert.deepEqual(db.prepare("SELECT status,accepted_count FROM auto_accept_history WHERE team_id=201 ORDER BY id").all(),
    [{ status: "success", accepted_count: 1 }, { status: "success", accepted_count: 0 }]);
  assert.equal(success.runner.hasPending(900), false);
  await success.runner.stop();

  // Proof generated by the real verifier must survive a runner restart. Reuse
  // updates the duplicate history without rewriting canonical evidence or alerts.
  const lostNotifications: AutoAcceptVerificationOutcome[] = [];
  await enqueue(job(202, "lost-a"));
  const first = worker(202, 4, lostNotifications);
  await drain(first.runner);
  const proofBefore = db.prepare("SELECT evidence_json,winning_attempt_trace_id FROM auto_accept_results WHERE team_id=202").get();
  await first.runner.stop();
  await enqueue(job(202, "lost-b"));
  const restarted = worker(202, null, lostNotifications);
  await drain(restarted.runner);
  assert.equal(restarted.reads(), 0, "durable, complete lost-race proof should avoid provider reads after restart");
  assert.equal((await listAutoAcceptVerificationJobs(202)).length, 0);
  assert.equal(lostNotifications.length, 1, "reuse must not send another failure notification");
  assert.deepEqual(db.prepare("SELECT evidence_json,winning_attempt_trace_id FROM auto_accept_results WHERE team_id=202").get(), proofBefore);
  assert.equal((db.prepare("SELECT need FROM notify_rules WHERE team_id=202").get() as { need: number }).need, 5);
  await restarted.runner.stop();

  const validProof = { source: "detached_verification", pendingTabRead: true, confirmedTabRead: true,
    observedStatuses: { 101: 4 }, verificationStartedAt: Date.now() - 1000 };
  const unsafeProofs = [
    { status: "lost", evidence: { ...validProof, confirmedTabRead: false } },
    { status: "lost", evidence: { ...validProof, pendingTabRead: false } },
    { status: "lost", evidence: { ...validProof, verificationStartedAt: undefined } },
    { status: "lost", evidence: { ...validProof, verificationStartedAt: 1 } },
    { status: "lost", evidence: { ...validProof, verificationStartedAt: Date.now() + 60_000 } },
    { status: "lost", evidence: { ...validProof, source: "legacy" } },
    { status: "lost", evidence: { ...validProof, observedStatuses: { 101: 6 } } },
    { status: "lost", evidence: { ...validProof, observedStatuses: { 102: 4 } } },
    { status: "lost", evidence: { ...validProof, verificationStartedAt: "100" } },
    { status: "lost", evidence: null },
    { status: "unknown", evidence: validProof },
    { status: "failed", evidence: validProof },
  ];
  for (const [index, sample] of unsafeProofs.entries()) {
    const teamId = 210 + index;
    canonical(teamId, sample.status, sample.evidence);
    await enqueue(job(teamId, `unsafe-${index}`));
    const probe = worker(teamId, null);
    await drain(probe.runner);
    const pending = await listAutoAcceptVerificationJobs(teamId);
    assert.equal(probe.reads(), 2, `unsafe evidence ${index} needs fresh provider reads`);
    assert.deepEqual(pending[0]?.unresolvedRequestIds, [101]);
    assert.equal(probe.runner.hasPending(900, 101), true);
    await probe.runner.stop();
  }

  canonical(230, "owned", null);
  await enqueue(job(230, "mixed", [101, 102]));
  const mixed = worker(230, null);
  await drain(mixed.runner);
  const mixedPending = (await listAutoAcceptVerificationJobs(230))[0]!;
  assert.equal(mixed.reads(), 2);
  assert.deepEqual(mixedPending.unresolvedRequestIds, [102], "only the unknown sibling retains a hold");
  assert.equal(verificationHoldCount(mixedPending), 1);
  assert.equal((db.prepare("SELECT need FROM notify_rules WHERE team_id=230").get() as { need: number }).need, 5);
  await mixed.runner.stop();

  canonical(231, "owned", null);
  await enqueue({ ...job(231, "discovery"), acceptAll: true, reservationCount: 5,
    discovery: { bookingName: "A-B", expectedAcceptedCount: 5 } });
  const discovery = worker(231, null);
  await drain(discovery.runner);
  const discoveryPending = (await listAutoAcceptVerificationJobs(231))[0]!;
  assert.equal(discovery.reads(), 2, "known ownership cannot bypass unfinished accept_all discovery");
  assert.equal(discoveryPending.discoveryPending, true);
  assert.ok(verificationHoldCount(discoveryPending) >= 4, "undiscovered sibling quota stays reserved");
  await discovery.runner.stop();

  // A matching request ID in another team or booking supplies no proof.
  canonical(240, "owned", null);
  canonical(241, "owned", null, 901);
  await enqueue(job(241, "scope"));
  const scoped = worker(241, null);
  await drain(scoped.runner);
  assert.equal(scoped.reads(), 2);
  assert.deepEqual((await listAutoAcceptVerificationJobs(241))[0]?.unresolvedRequestIds, [101]);
  await scoped.runner.stop();

  canonical(250, "lost", validProof);
  await createAutoAcceptVerificationIntent(job(250, "unacknowledged"), { postRecoveryDelayMs: 0 });
  const unacknowledged = worker(250, null);
  await drain(unacknowledged.runner);
  assert.equal(unacknowledged.reads(), 2, "placeholder POST finish cannot authorize reuse of a loss");
  assert.deepEqual((await listAutoAcceptVerificationJobs(250))[0]?.unresolvedRequestIds, [101]);
  await unacknowledged.runner.stop();

  canonical(251, "owned", null);
  await enqueue(job(251, "fenced"));
  const lease = await claimAutoAcceptVerificationJob(251, "fenced", { leaseMs: 1000 });
  assert.ok(lease?.leaseToken);
  assert.equal(await reuseAutoAcceptVerificationEvidence(251, "fenced", "wrong-token"), null);
  assert.equal(await reuseAutoAcceptVerificationEvidence(251, "fenced", lease.leaseToken, { now: lease.leaseUntil! }), null);
  assert.deepEqual((await listAutoAcceptVerificationJobs(251))[0]?.unresolvedRequestIds, [101]);

  // A pause arriving after the DB transaction must not strand its old in-memory
  // quota hold when the now-complete job will no longer appear in due queries.
  canonical(252, "owned", null);
  await enqueue(job(252, "pause-after-reuse"));
  let guards = 0;
  const synchronizedHolds: number[] = [];
  const paused = new AutoAcceptVerificationRunner(252, {
    fetchBookingRequestList: async () => assert.fail("owned proof needs no provider reads"),
  } as unknown as ApiClient, {
    canRun: () => ++guards <= 3,
    onHold: () => {},
    onSettled: record => { synchronizedHolds.push(verificationHoldCount(record)); },
    publish: async () => assert.fail("reusing ownership creates no new notification"),
  });
  await drain(paused);
  assert.equal((await listAutoAcceptVerificationJobs(252)).length, 0);
  assert.equal(paused.hasPending(900), false, "pause after commit cannot retain a stale pending index");
  assert.deepEqual(synchronizedHolds, [0], "the external budget hook must see the committed release");
  await paused.stop();

  canonical(253, "owned", null);
  await enqueue(job(253, "reuse-rollback"));
  const rollbackLease = await claimAutoAcceptVerificationJob(253, "reuse-rollback");
  assert.ok(rollbackLease?.leaseToken);
  db.exec("CREATE TRIGGER reject_reuse_save BEFORE UPDATE ON auto_accept_verification_jobs WHEN NEW.trace_id='reuse-rollback' BEGIN SELECT RAISE(ABORT,'injected save failure'); END");
  try {
    await assert.rejects(reuseAutoAcceptVerificationEvidence(253, "reuse-rollback", rollbackLease.leaseToken), /injected save failure/);
    assert.deepEqual(db.prepare("SELECT status,accepted_count FROM auto_accept_history WHERE team_id=253").get(),
      { status: "indeterminate", accepted_count: 0 }, "queue-save failure must roll back the history change");
    assert.deepEqual((await listAutoAcceptVerificationJobs(253))[0]?.unresolvedRequestIds, [101]);
  } finally { db.exec("DROP TRIGGER reject_reuse_save"); }

  await enqueue(job(254, "concurrent-booking-a"));
  await enqueue({ ...job(254, "concurrent-booking-b"), bookingId: 901 });
  let releaseReads!: () => void;
  const barrier = new Promise<void>(resolve => { releaseReads = resolve; });
  const startedBookings: number[] = [];
  const concurrent = new AutoAcceptVerificationRunner(254, {
    fetchBookingRequestList: async (bookingId: number) => {
      startedBookings.push(bookingId);
      await barrier;
      return { ...list(2), data: { ...list(2).data, request_list: [{ request_id: 101, booking_id: bookingId, request_acceptance_status: 2 }] } };
    },
  } as unknown as ApiClient, { canRun: () => true, onHold: () => {}, onSettled: () => {}, publish: async () => true });
  await concurrent.restore();
  await concurrent.runDue();
  for (let step = 0; step < 100 && startedBookings.length < 4; step++) await new Promise(resolve => setImmediate(resolve));
  try { assert.deepEqual(startedBookings.sort(), [900, 900, 901, 901], "unrelated bookings retain concurrent provider reads"); }
  finally { releaseReads(); await concurrent.idle(); await concurrent.stop(); }

  // The freshness boundary is the last read-pair start, never its completion.
  const realNow = Date.now;
  let clock = 100;
  let calls = 0;
  Date.now = () => clock;
  try {
    const outcome = await verifyAutoAcceptJob({ fetchBookingRequestList: async () => {
      calls++;
      clock = calls <= 2 ? 200 : 300;
      return { ...list(4), data: { ...list(4).data, request_list: [] } };
    } } as unknown as ApiClient, { ...job(260, "recheck-timestamp"), ambiguousAccept: true }, { ambiguousRecheckDelayMs: 0 });
    assert.equal(outcome.evidence.verificationStartedAt, 200);
    assert.equal(calls, 4);
  } finally { Date.now = realNow; }

  await closePool();
  console.log("verification reuse: concurrency, durable proof, unsafe evidence, holds and team scope passed");
}
main().catch(error => { console.error(error); process.exitCode = 1; });
