CREATE TABLE IF NOT EXISTS notify_rules (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  origins VARCHAR(4000) NOT NULL DEFAULT '[]',
  destinations VARCHAR(4000) NOT NULL DEFAULT '[]',
  vehicle_types VARCHAR(4000) NOT NULL DEFAULT '[]',
  need INT NOT NULL DEFAULT 1,
  enabled INT NOT NULL DEFAULT 1,
  fulfilled INT NOT NULL DEFAULT 0,
  auto_accept INT NOT NULL DEFAULT 0,
  auto_accepted INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
  updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()) ON UPDATE UTC_TIMESTAMP()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
