CREATE TABLE IF NOT EXISTS auto_accept_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  idempotency_key VARCHAR(512) NOT NULL,
  schema_version INT NOT NULL DEFAULT 1,
  team_id INT NOT NULL,
  booking_id BIGINT UNSIGNED NOT NULL,
  request_id BIGINT UNSIGNED NOT NULL,
  rule_id VARCHAR(255) NOT NULL,
  attempt_kind VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  payload_json TEXT NOT NULL,
  claim_owner VARCHAR(120) NULL,
  claim_token VARCHAR(80) NULL,
  claimed_at DATETIME NULL,
  claim_expires_at DATETIME NULL,
  last_heartbeat_at DATETIME NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  verify_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  next_run_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_error VARCHAR(1000) NULL,
  last_reason_code VARCHAR(64) NULL,
  winning_attempt_trace_id VARCHAR(160) NULL,
  result_status VARCHAR(32) NULL,
  result_reason_code VARCHAR(64) NULL,
  progress_settled_at DATETIME NULL,
  history_written_at DATETIME NULL,
  notification_enqueued_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  UNIQUE KEY aaj_idempotency_key_uidx (idempotency_key),
  KEY aaj_claimable_idx (status, next_run_at, claim_expires_at),
  KEY aaj_team_status_idx (team_id, status),
  KEY aaj_claim_owner_idx (claim_owner, claim_expires_at),
  KEY aaj_result_trace_idx (winning_attempt_trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
