CREATE TABLE IF NOT EXISTS realtime_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(255) NOT NULL,
  idempotency_key VARCHAR(512) NULL,
  event_type VARCHAR(64) NOT NULL,
  payload_version INT NOT NULL,
  envelope_version INT NOT NULL,
  scope_kind VARCHAR(16) NOT NULL,
  team_id INT NULL,
  subject_type VARCHAR(64) NULL,
  subject_id VARCHAR(160) NULL,
  source_service VARCHAR(64) NOT NULL,
  source_node_id VARCHAR(120) NOT NULL,
  source_role VARCHAR(64) NOT NULL,
  trace_id VARCHAR(160) NULL,
  replayable INT NOT NULL DEFAULT 0,
  payload_json TEXT NOT NULL,
  envelope_json TEXT NOT NULL,
  emitted_at DATETIME NOT NULL,
  received_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY realtime_events_event_id_uidx (event_id),
  UNIQUE KEY realtime_events_idempotency_key_uidx (idempotency_key),
  KEY realtime_events_scope_team_id_idx (scope_kind, team_id, id),
  KEY realtime_events_type_received_idx (event_type, received_at),
  KEY realtime_events_source_node_received_idx (source_node_id, received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
