CREATE TABLE gate6_environment_slots (
  environment VARCHAR(32) NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  owner_id VARCHAR(128) NOT NULL,
  operation_id VARCHAR(128) NOT NULL,
  transfer_token_sha256 CHAR(64) NULL,
  state VARCHAR(40) NOT NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  uncompensated_work TINYINT(1) NOT NULL DEFAULT 0,
  protected_install_evidence_sha256 CHAR(64) NOT NULL,
  release_sha CHAR(40) NOT NULL,
  target_descriptor_sha256 CHAR(64) NOT NULL,
  operator_bundle_sha256 CHAR(64) NOT NULL,
  installed_migration_set_sha256 CHAR(64) NOT NULL,
  installed_schema_version INT UNSIGNED NOT NULL,
  heartbeat_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (environment),
  UNIQUE KEY gate6_slot_owner_uq (owner_type, owner_id),
  KEY gate6_slot_state_expiry_idx (state, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;

CREATE TABLE gate6_runs (
  gate6_id VARCHAR(128) NOT NULL,
  gate6_nonce VARCHAR(128) NOT NULL,
  envelope_sha256 CHAR(64) NOT NULL,
  envelope_core_sha256 CHAR(64) NOT NULL,
  release_environment VARCHAR(32) NOT NULL,
  runtime_environment VARCHAR(32) NOT NULL,
  drill_mode VARCHAR(40) NOT NULL,
  compose_project VARCHAR(64) NOT NULL,
  candidate_sha CHAR(40) NOT NULL,
  candidate_image_digest VARCHAR(80) NOT NULL,
  rollback_sha CHAR(40) NOT NULL,
  rollback_image_digest VARCHAR(80) NOT NULL,
  production_target_descriptor_sha256 CHAR(64) NOT NULL,
  operator_bundle_sha256 CHAR(64) NOT NULL,
  protected_install_evidence_sha256 CHAR(64) NOT NULL,
  installed_migration_set_sha256 CHAR(64) NOT NULL,
  installed_schema_version INT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL,
  current_stage VARCHAR(64) NOT NULL,
  stage_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  accepted_checker_name VARCHAR(128) NULL,
  accepted_checker_sha256 CHAR(64) NULL,
  revocation_reason_code VARCHAR(80) NULL,
  monitor_status VARCHAR(16) NOT NULL,
  monitor_lease_expires_at DATETIME(3) NOT NULL,
  supervisor_status VARCHAR(16) NOT NULL,
  supervisor_lease_expires_at DATETIME(3) NOT NULL,
  emergency_supervisor_lease_expires_at DATETIME(3) NOT NULL,
  terminal_evidence_sha256 CHAR(64) NULL,
  expires_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (gate6_id),
  UNIQUE KEY gate6_runs_envelope_uq (envelope_sha256),
  UNIQUE KEY gate6_runs_nonce_uq (gate6_nonce),
  KEY gate6_runs_status_expiry_idx (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;

CREATE TABLE gate6_actions (
  gate6_id VARCHAR(128) NOT NULL,
  scope VARCHAR(128) NOT NULL,
  action_id VARCHAR(128) NOT NULL,
  approval_sha256 CHAR(64) NOT NULL,
  allowed_mutation_sha256 CHAR(64) NOT NULL,
  kind VARCHAR(24) NOT NULL,
  paired_action_id VARCHAR(128) NULL,
  predecessor_action_ids_json JSON NOT NULL,
  required_stage VARCHAR(64) NOT NULL,
  required_checker_sha256 CHAR(64) NULL,
  status VARCHAR(24) NOT NULL,
  before_evidence_sha256 CHAR(64) NULL,
  after_evidence_sha256 CHAR(64) NULL,
  expires_at DATETIME(3) NOT NULL,
  consumed_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (gate6_id, scope, action_id),
  UNIQUE KEY gate6_actions_id_uq (gate6_id, action_id),
  KEY gate6_actions_status_expiry_idx (gate6_id, status, expires_at),
  CONSTRAINT gate6_actions_run_fk FOREIGN KEY (gate6_id) REFERENCES gate6_runs (gate6_id)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;

CREATE TABLE gate6_fault_permits (
  permit_id VARCHAR(128) NOT NULL,
  gate6_id VARCHAR(128) NOT NULL,
  scope VARCHAR(128) NOT NULL,
  action_id VARCHAR(128) NOT NULL,
  service VARCHAR(32) NOT NULL,
  kind VARCHAR(64) NOT NULL,
  team_id INT UNSIGNED NOT NULL,
  drill_sha256 CHAR(64) NOT NULL,
  target_sha256 CHAR(64) NULL,
  fixture_sha256 CHAR(64) NULL,
  signed_permit_sha256 CHAR(64) NOT NULL,
  verification_key_id VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  consumed_at DATETIME(3) NULL,
  disarmed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (permit_id),
  UNIQUE KEY gate6_permit_action_uq (gate6_id, scope, action_id),
  KEY gate6_permit_status_expiry_idx (gate6_id, status, expires_at),
  CONSTRAINT gate6_permit_action_fk FOREIGN KEY (gate6_id, scope, action_id)
    REFERENCES gate6_actions (gate6_id, scope, action_id)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;

CREATE OR REPLACE SQL SECURITY DEFINER VIEW operational_gate6_terminal_evidence AS
SELECT
  r.gate6_id,
  r.candidate_sha,
  r.candidate_image_digest,
  r.rollback_sha,
  r.rollback_image_digest,
  r.production_target_descriptor_sha256,
  r.operator_bundle_sha256,
  r.installed_migration_set_sha256,
  r.installed_schema_version,
  r.status AS run_status,
  r.current_stage,
  r.stage_version,
  r.accepted_checker_name,
  r.accepted_checker_sha256,
  s.owner_type AS slot_owner_type,
  s.owner_id AS slot_owner_id,
  s.state AS slot_state,
  s.uncompensated_work,
  COALESCE(a.forward_registered_count, 0) AS forward_registered_count,
  COALESCE(a.forward_consumed_count, 0) AS forward_consumed_count,
  COALESCE(a.forward_succeeded_count, 0) AS forward_succeeded_count,
  COALESCE(a.forward_failed_count, 0) AS forward_failed_count,
  COALESCE(a.forward_ambiguous_count, 0) AS forward_ambiguous_count,
  COALESCE(a.forward_compensated_count, 0) AS forward_compensated_count,
  COALESCE(a.compensation_registered_count, 0) AS compensation_registered_count,
  COALESCE(a.compensation_consumed_count, 0) AS compensation_consumed_count,
  COALESCE(a.compensation_succeeded_count, 0) AS compensation_succeeded_count,
  COALESCE(a.compensation_failed_count, 0) AS compensation_failed_count,
  COALESCE(a.compensation_ambiguous_count, 0) AS compensation_ambiguous_count,
  COALESCE(a.compensation_compensated_count, 0) AS compensation_compensated_count,
  COALESCE(a.compensation_not_needed_count, 0) AS compensation_not_needed_count,
  COALESCE(a.emergency_registered_count, 0) AS emergency_registered_count,
  COALESCE(a.emergency_consumed_count, 0) AS emergency_consumed_count,
  COALESCE(a.emergency_succeeded_count, 0) AS emergency_succeeded_count,
  COALESCE(a.emergency_failed_count, 0) AS emergency_failed_count,
  COALESCE(a.emergency_ambiguous_count, 0) AS emergency_ambiguous_count,
  COALESCE(p.active_permit_count, 0) AS active_permit_count,
  r.terminal_evidence_sha256,
  r.created_at,
  r.updated_at
FROM gate6_runs r
JOIN gate6_environment_slots s
  ON s.environment = 'production' AND s.owner_type = 'gate6' AND s.owner_id = r.gate6_id
LEFT JOIN (
  SELECT
    gate6_id,
    SUM(kind = 'forward' AND status = 'registered') AS forward_registered_count,
    SUM(kind = 'forward' AND status = 'consumed') AS forward_consumed_count,
    SUM(kind = 'forward' AND status = 'succeeded') AS forward_succeeded_count,
    SUM(kind = 'forward' AND status = 'failed') AS forward_failed_count,
    SUM(kind = 'forward' AND status = 'ambiguous') AS forward_ambiguous_count,
    SUM(kind = 'forward' AND status = 'compensated') AS forward_compensated_count,
    SUM(kind = 'compensation' AND status = 'registered') AS compensation_registered_count,
    SUM(kind = 'compensation' AND status = 'consumed') AS compensation_consumed_count,
    SUM(kind = 'compensation' AND status = 'succeeded') AS compensation_succeeded_count,
    SUM(kind = 'compensation' AND status = 'failed') AS compensation_failed_count,
    SUM(kind = 'compensation' AND status = 'ambiguous') AS compensation_ambiguous_count,
    SUM(kind = 'compensation' AND status = 'compensated') AS compensation_compensated_count,
    SUM(kind = 'compensation' AND status = 'not_needed') AS compensation_not_needed_count,
    SUM(kind = 'emergency' AND status = 'registered') AS emergency_registered_count,
    SUM(kind = 'emergency' AND status = 'consumed') AS emergency_consumed_count,
    SUM(kind = 'emergency' AND status = 'succeeded') AS emergency_succeeded_count,
    SUM(kind = 'emergency' AND status = 'failed') AS emergency_failed_count,
    SUM(kind = 'emergency' AND status = 'ambiguous') AS emergency_ambiguous_count
  FROM gate6_actions
  GROUP BY gate6_id
) a ON a.gate6_id = r.gate6_id
LEFT JOIN (
  SELECT gate6_id, SUM(status = 'armed') AS active_permit_count
  FROM gate6_fault_permits
  GROUP BY gate6_id
) p ON p.gate6_id = r.gate6_id;
