export function buildDashboardHtml(): string {
  return `<!DOCTYPE html>
<html lang="th" data-bs-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="dark">
<title>SPX Bidding — Control Center</title>
<link rel="preconnect" href="https://cdn.jsdelivr.net">
<link rel="preconnect" href="https://code.jquery.com">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.bootstrap5.min.css" rel="stylesheet">
<style>
  :root { --bg:#0b1020; --panel:rgba(17,24,45,.9); --border:rgba(148,163,184,.16); --text:#e5e7eb; --muted:#94a3b8; --accent:#7dd3fc; --accent-2:#a78bfa; }
  *{box-sizing:border-box} body{min-height:100vh;color:var(--text);background:linear-gradient(180deg,#09101d 0%,#0b1020 45%,#050816 100%);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
  .shell{position:relative;overflow:hidden}.surface,.hero-card{background:var(--panel);border:1px solid var(--border);border-radius:20px;backdrop-filter:blur(14px);box-shadow:0 18px 60px rgba(0,0,0,.35)}
  .hero-card{padding:22px}.topbar{backdrop-filter:blur(16px);background:rgba(7,11,22,.72);border-bottom:1px solid var(--border)}.brand{font-weight:800}.dot{display:inline-block;width:10px;height:10px;border-radius:999px;background:linear-gradient(135deg,var(--accent),var(--accent-2));margin-right:10px}
  .kpis{margin-top:18px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.kpi{padding:16px;border-radius:18px;border:1px solid var(--border);background:rgba(255,255,255,.03)}.kpi .label{color:var(--muted);font-size:.82rem}.kpi .value{font-size:1.5rem;font-weight:800;margin-top:6px}.kpi .hint{color:var(--muted);font-size:.8rem;margin-top:4px}
  .nav-tabs{border-bottom:0;gap:8px;flex-wrap:wrap}.nav-tabs .nav-link{border:1px solid var(--border);background:rgba(255,255,255,.03);color:var(--muted);border-radius:14px;padding:12px 16px;font-weight:650}.nav-tabs .nav-link.active{color:#fff;background:linear-gradient(135deg,rgba(125,211,252,.2),rgba(167,139,250,.18));border-color:rgba(125,211,252,.35)}
  .table{color:var(--text);--bs-table-bg:transparent}.table thead th{color:#cbd5e1;border-bottom-color:rgba(255,255,255,.1)!important;font-weight:700;text-transform:uppercase;font-size:.74rem;letter-spacing:.08em}.table td,.table th{border-color:rgba(255,255,255,.08)!important}.table-hover>tbody>tr:hover>*{background:rgba(125,211,252,.06)}
  .form-control,.input-group-text{background-color:rgba(8,13,28,.88);border-color:rgba(148,163,184,.18);color:#fff}.form-control:focus{background-color:rgba(8,13,28,.96);color:#fff;border-color:rgba(125,211,252,.55);box-shadow:0 0 0 .18rem rgba(125,211,252,.14)}
  .toast-container{position:fixed;bottom:18px;right:18px;z-index:1055}.badge-soft{background:rgba(255,255,255,.08);color:#fff;border:1px solid rgba(255,255,255,.09)}
</style>
</head>
<body>
<div class="shell">
  <nav class="navbar navbar-expand-lg topbar sticky-top"><div class="container-fluid px-3 px-lg-4 py-2"><a class="navbar-brand brand text-white" href="#"><span class="dot"></span>SPX Control Center</a><div class="ms-auto d-flex gap-2 align-items-center flex-wrap"><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#addRuleModal">➕ เพิ่มรายการ</button><button class="btn btn-sm btn-outline-light" onclick="window.location.reload()">⟳ รีเฟรช</button><button class="btn btn-sm btn-outline-danger" onclick="logout()">🚪 ออกจากระบบ</button></div></div></nav>
  <main class="container-fluid px-3 px-lg-4 pb-4">
    <section class="hero mt-4"><div class="hero-card"><div class="eyebrow text-uppercase text-secondary small" style="letter-spacing:.18em">Real-time bidding dashboard</div><h1 class="mt-2 fw-bold">มุมมองเดียวสำหรับติดตามงาน, บริหาร rule, และคุมระบบแบบปลอดภัย</h1><p class="text-secondary mb-0">ศูนย์กลางการปฏิบัติการของ SPX Bidding Poller ที่รวมการค้นหา, ประวัติงาน, audit log, ผู้ใช้งาน และ settings ไว้ในพื้นที่เดียว</p><div class="kpis"><div class="kpi"><div class="label">รายการรอค้นหา</div><div class="value" id="kpi-active">—</div><div class="hint">Rule ที่ยังเปิดอยู่</div></div><div class="kpi"><div class="label">รายการครบแล้ว</div><div class="value" id="kpi-done">—</div><div class="hint">Rule ที่ fulfilled แล้ว</div></div><div class="kpi"><div class="label">รายการปิด</div><div class="value" id="kpi-off">—</div><div class="hint">Rule ที่ปิดการค้นหา</div></div><div class="kpi"><div class="label">สถานะระบบ</div><div class="value" id="kpi-status">Ready</div><div class="hint" id="kpi-status-hint">เชื่อมต่อผ่าน API</div></div></div><div class="kpis mt-3"><div class="kpi"><div class="label">Uptime</div><div class="value" id="metric-uptime">—</div><div class="hint">เวลาที่ระบบทำงานต่อเนื่อง</div></div><div class="kpi"><div class="label">Success rate</div><div class="value" id="metric-success-rate">—</div><div class="hint">อัตราความสำเร็จของ polling</div></div><div class="kpi"><div class="label">Latency p95</div><div class="value" id="metric-p95">—</div><div class="hint">เวลา response ที่ช้าในกลุ่ม 95%</div></div><div class="kpi"><div class="label">Last poll</div><div class="value" id="metric-last-poll">—</div><div class="hint" id="metric-last-status">ยังไม่มีข้อมูล</div></div></div></div></section>
    <div class="my-4"><ul class="nav nav-tabs" id="myTab" role="tablist"><li class="nav-item"><button class="nav-link active" id="rules-tab" data-bs-toggle="tab" data-bs-target="#rules-pane" type="button">รายการค้นหาทั้งหมด</button></li><li class="nav-item"><button class="nav-link" id="history-tab" data-bs-toggle="tab" data-bs-target="#history-pane" type="button">ประวัติงานใน DB</button></li><li class="nav-item"><button class="nav-link" id="audit-tab" data-bs-toggle="tab" data-bs-target="#audit-pane" type="button">ประวัติการใช้งาน</button></li><li class="nav-item"><button class="nav-link" id="users-tab" data-bs-toggle="tab" data-bs-target="#users-pane" type="button">จัดการผู้ใช้งาน</button></li><li class="nav-item"><button class="nav-link" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings-pane" type="button">ตั้งค่าระบบ</button></li><li class="nav-item"><button class="nav-link" id="notifications-tab" data-bs-toggle="tab" data-bs-target="#notifications-pane" type="button">แจ้งเตือน</button></li><li class="nav-item"><button class="nav-link" id="reports-tab" data-bs-toggle="tab" data-bs-target="#reports-pane" type="button">รายงาน</button></li></ul></div>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="rules-pane" role="tabpanel"><div class="surface p-3"><div class="section-head d-flex justify-content-between"><div><h5>รายการค้นหา</h5><p>จัดการ rule และดูสถานะได้ทันที</p></div><div id="stats" class="small fw-bold"></div></div><table id="rulesTable" class="table table-hover nowrap w-100"><thead><tr><th>สถานะ</th><th>ชื่อรายการ</th><th>ต้นทาง</th><th>ปลายทาง</th><th>ประเภทรถ</th><th>ต้องการ</th><th>จัดการ</th></tr></thead><tbody></tbody></table></div></div>
      <div class="tab-pane fade" id="history-pane" role="tabpanel"><div class="surface p-3"><div class="d-flex flex-wrap gap-2 justify-content-between align-items-end mb-3"><div><h5 class="mb-1">ประวัติงานใน DB</h5><p class="text-secondary mb-0">ค้นหา / filter / sort รายการย้อนหลัง</p></div><div class="d-flex flex-wrap gap-2"><input id="history-search" class="form-control form-control-sm" placeholder="ค้นหา"><input id="history-origin" class="form-control form-control-sm" placeholder="ต้นทาง"><input id="history-destination" class="form-control form-control-sm" placeholder="ปลายทาง"><input id="history-vehicle" class="form-control form-control-sm" placeholder="ประเภทรถ"><button class="btn btn-sm btn-outline-light" onclick="refreshHistory()">ค้นหา</button><button class="btn btn-sm btn-outline-light" onclick="resetHistoryFilters()">ล้าง</button></div></div><table id="historyTable" class="table table-hover nowrap w-100"><thead><tr><th>Request ID</th><th>Booking ID</th><th>ต้นทาง</th><th>ปลายทาง</th><th>ประเภทรถ</th><th>เวลาสแตนบาย</th><th>บันทึกเมื่อ</th></tr></thead><tbody></tbody></table></div></div>
      <div class="tab-pane fade" id="audit-pane" role="tabpanel"><div class="surface p-3"><div class="d-flex flex-wrap gap-2 justify-content-between align-items-end mb-3"><div><h5 class="mb-1">ประวัติการใช้งาน</h5><p class="text-secondary mb-0">ค้นหาและกรองกิจกรรมผู้ใช้</p></div><div class="d-flex flex-wrap gap-2"><input id="audit-search" class="form-control form-control-sm" placeholder="ค้นหา"><input id="audit-username" class="form-control form-control-sm" placeholder="username"><input id="audit-action" class="form-control form-control-sm" placeholder="action"><button class="btn btn-sm btn-outline-light" onclick="refreshAudit()">ค้นหา</button><button class="btn btn-sm btn-outline-light" onclick="resetAuditFilters()">ล้าง</button></div></div><table id="auditTable" class="table table-hover nowrap w-100"><thead><tr><th>ID</th><th>ผู้ทำรายการ</th><th>แอคชัน</th><th>รายละเอียด</th><th>เวลา</th></tr></thead><tbody></tbody></table></div></div>
      <div class="tab-pane fade" id="users-pane" role="tabpanel"><div class="surface p-3"><div class="section-head d-flex justify-content-between"><div><h5>จัดการผู้ใช้งาน</h5><p>เพิ่มผู้ใช้ใหม่ เปลี่ยนรหัสผ่าน และกำหนด role</p></div><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#addUserModal">➕ เพิ่มผู้ใช้งาน</button></div><table id="usersTable" class="table table-hover nowrap w-100"><thead><tr><th>ID</th><th>ชื่อผู้ใช้</th><th>Role</th><th>วันที่สร้าง</th><th>จัดการ</th></tr></thead><tbody></tbody></table></div></div>
      <div class="tab-pane fade" id="settings-pane" role="tabpanel"><div class="surface p-4 mx-auto" style="max-width:900px;"><h5 class="mb-3">ตั้งค่าระบบ</h5><form id="settingsForm" onsubmit="event.preventDefault(); saveSettings();"><div class="mb-3"><label class="form-label text-secondary small text-uppercase">SPX API URL</label><input type="text" id="s-api-url" class="form-control"></div><div class="mb-3"><label class="form-label text-secondary small text-uppercase">POLL_INTERVAL_MS</label><input type="number" id="s-poll-interval" class="form-control"></div><div class="mb-3"><label class="form-label text-secondary small text-uppercase">Cookie</label><textarea id="s-cookie" class="form-control" rows="3"></textarea></div><div class="mb-3"><label class="form-label text-secondary small text-uppercase">Device ID</label><input type="text" id="s-device-id" class="form-control"></div><hr class="border-secondary my-4"><div class="mb-3"><label class="form-label text-secondary small text-uppercase">LINE Notify Token</label><input type="text" id="s-line-token" class="form-control"></div><div class="mb-3"><label class="form-label text-secondary small text-uppercase">Discord Webhook URL</label><input type="text" id="s-discord-url" class="form-control"></div><div class="text-end"><button type="submit" class="btn btn-success px-4">💾 บันทึกการตั้งค่า</button></div></form></div></div>
      <div class="tab-pane fade" id="notifications-pane" role="tabpanel"><div class="surface p-4"><h5 class="mb-3">Notification preview / test</h5><div class="d-flex gap-2 flex-wrap"><button class="btn btn-primary" onclick="previewNotification()">Preview</button><button class="btn btn-outline-light" onclick="testNotification()">Send Test</button></div><pre class="mt-3 p-3 rounded-3" id="notification-preview" style="background:rgba(255,255,255,.04);white-space:pre-wrap"></pre></div></div>
      <div class="tab-pane fade" id="reports-pane" role="tabpanel"><div class="surface p-4"><h5 class="mb-3">Export รายงาน</h5><div class="d-flex gap-2 flex-wrap"><button class="btn btn-outline-light" onclick="downloadReport('/reports/metrics.csv','spx-metrics.csv')">Export metrics</button><button class="btn btn-outline-light" onclick="downloadReport('/reports/history.csv','spx-history.csv')">Export history</button><button class="btn btn-outline-light" onclick="downloadReport('/reports/audit.csv','spx-audit.csv')">Export audit</button></div></div></div>
    </div>
  </main>
</div>

<div class="modal fade" id="addRuleModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h1 class="modal-title fs-5">➕ เพิ่ม / แก้ไขรายการค้นหา</h1><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="rule-id"><div class="mb-3"><label class="form-label text-secondary small text-uppercase">ชื่อรายการ</label><input type="text" id="f-name" class="form-control"></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label text-secondary small text-uppercase">ต้นทาง (คั่นด้วย ,)</label><input type="text" id="f-origins" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label text-secondary small text-uppercase">ปลายทาง (คั่นด้วย ,)</label><input type="text" id="f-destinations" class="form-control"></div></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label text-secondary small text-uppercase">ประเภทรถ (คั่นด้วย ,)</label><input type="text" id="f-vehicle" class="form-control"></div><div class="col-md-3 mb-3"><label class="form-label text-secondary small text-uppercase">จำนวน</label><input type="number" id="f-need" class="form-control" min="1" value="1"></div><div class="col-md-3 mb-3"><label class="form-label text-secondary small text-uppercase">สถานะ</label><select id="f-enabled" class="form-select"><option value="true">เปิด</option><option value="false">ปิด</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button><button type="button" class="btn btn-primary" onclick="saveRule()">บันทึก</button></div></div></div></div>

<div class="modal fade" id="addUserModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h1 class="modal-title fs-5">➕ เพิ่มผู้ใช้งานใหม่</h1><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label text-secondary small text-uppercase">ชื่อผู้ใช้</label><input type="text" id="u-username" class="form-control"></div><div class="mb-3"><label class="form-label text-secondary small text-uppercase">รหัสผ่าน</label><input type="password" id="u-password" class="form-control"></div><div class="mb-3"><label class="form-label text-secondary small text-uppercase">Role</label><select id="u-role" class="form-select"><option value="viewer">viewer</option><option value="editor">editor</option><option value="admin">admin</option></select></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button><button type="button" class="btn btn-primary" onclick="addUser()">เพิ่มผู้ใช้งาน</button></div></div></div></div>

<div class="modal fade" id="changePasswordModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h1 class="modal-title fs-5">🔑 เปลี่ยนรหัสผ่าน</h1><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="pwd-user-id"><div class="mb-3"><label class="form-label text-secondary small text-uppercase">รหัสผ่านใหม่</label><input type="password" id="pwd-new" class="form-control"></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button><button type="button" class="btn btn-warning" onclick="changePassword()">เปลี่ยนรหัสผ่าน</button></div></div></div></div>
<div class="toast-container" id="toast-container"></div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script><script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script><script src="https://cdn.datatables.net/responsive/2.5.0/js/responsive.bootstrap5.min.js"></script>
<script src="/assets/dashboard.js"></script>
</body>
</html>`;
}
