export function buildDashboardHtml(): string {
  return /* html */ `<!DOCTYPE html>
<html lang="th" data-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="dark">
<title>SPX Bidding — Control Center</title>
<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
<style>
  :root { color-scheme: dark; --spx-bg:#020617; --spx-surface:rgba(15,23,42,.72); --spx-surface-strong:rgba(15,23,42,.88); --spx-border:rgba(255,255,255,.1); --spx-border-soft:rgba(255,255,255,.08); --spx-muted:#94a3b8; --spx-text:#e5e7eb; }
  html[data-theme="light"] { color-scheme: light; --spx-bg:#f8fafc; --spx-surface:rgba(255,255,255,.82); --spx-surface-strong:rgba(255,255,255,.94); --spx-border:rgba(15,23,42,.12); --spx-border-soft:rgba(15,23,42,.08); --spx-muted:#475569; --spx-text:#0f172a; }
  body { min-height:100vh; font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; background: radial-gradient(circle at top, rgba(34,211,238,.12), transparent 32%), radial-gradient(circle at 85% 18%, rgba(168,85,247,.14), transparent 25%), linear-gradient(180deg, var(--spx-bg) 0%, color-mix(in srgb, var(--spx-bg) 85%, #0f172a 15%) 45%, var(--spx-bg) 100%); color:var(--spx-text); }
  .glass,.panel,.grid-shell,.metric{border:1px solid var(--spx-border-soft);background:var(--spx-surface);backdrop-filter:blur(16px);box-shadow:0 24px 80px rgba(2,6,23,.22)}
  .tab-btn.active{background:linear-gradient(135deg,rgba(34,211,238,.22),rgba(168,85,247,.18));border-color:rgba(125,211,252,.3);color:#fff}
  .sse-dot{display:inline-block;width:8px;height:8px;border-radius:999px;margin-right:6px;vertical-align:middle;transition:background .3s}.sse-dot.connected{background:#22c55e;box-shadow:0 0 6px #22c55e80}.sse-dot.disconnected{background:#ef4444;box-shadow:0 0 6px #ef444480}.sse-dot.connecting{background:#eab308;animation:blink 1s infinite}
  @keyframes blink{0%,100%{opacity:1}50%{opacity:.3}}
  .toast-container{position:fixed;bottom:18px;right:18px;z-index:1055}
  .grid-toolbar{display:flex;flex-wrap:wrap;gap:.75rem;align-items:center;justify-content:space-between;margin-bottom:1rem}
  .filters{display:flex;flex-wrap:wrap;gap:.5rem;align-items:center}
  .grid-search,.grid-filter,.grid-select{background:color-mix(in srgb,var(--spx-bg) 82%,#1e293b 18%);color:var(--spx-text);border:1px solid var(--spx-border);border-radius:999px;padding:.65rem .95rem;outline:none}
  .grid-search::placeholder,.grid-filter::placeholder{color:var(--spx-muted)}
  .grid-table{width:100%;border-collapse:separate;border-spacing:0}
  .grid-table thead th{position:sticky;top:0;z-index:1;background:color-mix(in srgb,var(--spx-bg) 86%,#0f172a 14%);color:#cbd5e1;text-align:left;font-size:.72rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase;padding:1rem .9rem;border-bottom:1px solid var(--spx-border)}
  html[data-theme="light"] .grid-table thead th{color:#334155}
  .grid-table thead th[data-sortable="true"]{cursor:pointer;user-select:none}.grid-table thead th[data-sortable="true"]:hover{color:#67e8f9}.grid-table thead th .sort-indicator{display:inline-flex;align-items:center;gap:.3rem}.grid-table thead th .sort-arrow{opacity:.35;font-size:.7rem;line-height:1}.grid-table thead th.is-sorted .sort-arrow{opacity:1;color:#67e8f9}
  .grid-table tbody td{padding:.95rem .9rem;border-bottom:1px solid var(--spx-border-soft);vertical-align:top}.grid-table tbody tr:hover td{background:rgba(34,211,238,.06)}
  .grid-empty{display:grid;place-items:center;min-height:240px;color:var(--spx-muted);text-align:center;padding:2rem}
  .pager-btn{border:1px solid var(--spx-border);background:rgba(255,255,255,.04);color:var(--spx-text);border-radius:999px;padding:.45rem .8rem}.pager-btn:disabled{opacity:.45;cursor:not-allowed}
  .col-hide-sm{display:table-cell}@media (max-width: 768px){.col-hide-sm{display:none}}
</style>
</head>
<body class="antialiased">
<div class="min-h-screen">
  <nav class="sticky top-0 z-30 border-b border-white/10 bg-slate-950/70 backdrop-blur-xl">
    <div class="mx-auto flex max-w-[1600px] flex-wrap items-center gap-3 px-4 py-3 sm:px-6 lg:px-8">
      <div class="flex items-center gap-2 font-extrabold tracking-tight text-white"><span class="h-3 w-3 rounded-full bg-gradient-to-r from-cyan-400 to-violet-500"></span>SPX Control Center</div>
      <div class="ml-auto flex flex-wrap items-center gap-2 text-sm text-slate-300">
        <button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-medium text-white transition hover:bg-white/10" id="theme-toggle" type="button">Theme</button>
        <span id="sse-status"><span class="sse-dot connecting" id="sse-dot"></span><span id="sse-label" aria-live="polite">connecting...</span></span>
        <button class="rounded-xl border border-cyan-400/20 bg-cyan-400/10 px-3 py-2 font-medium text-cyan-100 transition hover:bg-cyan-400/15" id="add-rule-button" data-bs-toggle="modal" data-bs-target="#addRuleModal" type="button">➕ เพิ่มรายการ</button>
        <button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-medium text-white transition hover:bg-white/10" id="refresh-page-button" type="button">⟳ รีเฟรช</button>
        <button class="rounded-xl border border-rose-500/20 bg-rose-500/10 px-3 py-2 font-medium text-rose-100 transition hover:bg-rose-500/15" id="logout-button" type="button">🚪 ออกจากระบบ</button>
      </div>
    </div>
  </nav>
  <main class="mx-auto max-w-[1600px] px-4 py-5 sm:px-6 lg:px-8">
    <section class="glass rounded-[2rem] p-5 sm:p-7">
      <div class="max-w-4xl"><div class="inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200">Real-time bidding dashboard</div><h1 class="mt-5 text-3xl font-black tracking-tight sm:text-4xl">มุมมองเดียวสำหรับติดตามงาน, บริหาร rule, และคุมระบบแบบปลอดภัย</h1><p class="mt-3 text-sm leading-6 text-slate-300 sm:text-base">ศูนย์กลางการปฏิบัติการของ SPX Bidding Poller ที่รวมการค้นหา, ประวัติงาน, audit log, ผู้ใช้งาน และ settings ไว้ในพื้นที่เดียว</p></div>
      <div class="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">รายการรอค้นหา</div><div class="mt-2 text-2xl font-extrabold" id="kpi-active">—</div><div class="mt-1 text-sm text-slate-400">Rule ที่ยังเปิดอยู่</div></div><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">รายการครบแล้ว</div><div class="mt-2 text-2xl font-extrabold" id="kpi-done">—</div><div class="mt-1 text-sm text-slate-400">Rule ที่ fulfilled แล้ว</div></div><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">รายการปิด</div><div class="mt-2 text-2xl font-extrabold" id="kpi-off">—</div><div class="mt-1 text-sm text-slate-400">Rule ที่ปิดการค้นหา</div></div><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">สถานะระบบ</div><div class="mt-2 text-2xl font-extrabold" id="kpi-status">Ready</div><div class="mt-1 text-sm text-slate-400" id="kpi-status-hint">เชื่อมต่อผ่าน API</div></div></div>
      <div class="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">Uptime</div><div class="mt-2 text-2xl font-extrabold" id="metric-uptime">—</div><div class="mt-1 text-sm text-slate-400">เวลาที่ระบบทำงานต่อเนื่อง</div></div><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">Success rate</div><div class="mt-2 text-2xl font-extrabold" id="metric-success-rate">—</div><div class="mt-1 text-sm text-slate-400">อัตราความสำเร็จของ polling</div></div><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">Latency p95</div><div class="mt-2 text-2xl font-extrabold" id="metric-p95">—</div><div class="mt-1 text-sm text-slate-400">เวลา response ที่ช้าในกลุ่ม 95%</div></div><div class="metric rounded-2xl p-4"><div class="text-xs uppercase tracking-[0.2em] text-slate-400">Last poll</div><div class="mt-2 text-2xl font-extrabold" id="metric-last-poll">—</div><div class="mt-1 text-sm text-slate-400" id="metric-last-status">ยังไม่มีข้อมูล</div></div></div>
    </section>
    <section class="mt-4 grid gap-4 xl:grid-cols-2"><div class="glass rounded-[1.75rem] p-4"><h6 class="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Polling Latency (ms)</h6><canvas id="chart-latency" role="img" aria-label="Polling latency chart showing p95 and average response time"></canvas></div><div class="glass rounded-[1.75rem] p-4"><h6 class="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Success Rate (%)</h6><canvas id="chart-success" role="img" aria-label="Polling success rate percentage over time"></canvas></div></section>
    <div class="mt-4 flex flex-wrap gap-2"><button class="tab-btn active rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition" id="rules-tab" data-bs-toggle="tab" data-bs-target="#rules-pane" type="button">รายการค้นหาทั้งหมด</button><button class="tab-btn rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition" id="history-tab" data-bs-toggle="tab" data-bs-target="#history-pane" type="button">ประวัติงานใน DB</button><button class="tab-btn rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition" id="audit-tab" data-bs-toggle="tab" data-bs-target="#audit-pane" type="button">ประวัติการใช้งาน</button><button class="tab-btn rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition" id="users-tab" data-bs-toggle="tab" data-bs-target="#users-pane" type="button">จัดการผู้ใช้งาน</button><button class="tab-btn rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings-pane" type="button">ตั้งค่าระบบ</button><button class="tab-btn rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition" id="notifications-tab" data-bs-toggle="tab" data-bs-target="#notifications-pane" type="button">แจ้งเตือน</button><button class="tab-btn rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition" id="reports-tab" data-bs-toggle="tab" data-bs-target="#reports-pane" type="button">รายงาน</button></div>
    <div class="tab-content mt-4" id="myTabContent">
      <div class="tab-pane fade show active" id="rules-pane" role="tabpanel">${tableCard('rules','รายการค้นหา','จัดการ rule และดูสถานะได้ทันที','rulesTable',[{id:'status',label:'สถานะ'},{id:'name',label:'ชื่อรายการ'},{id:'origins',label:'ต้นทาง'},{id:'destinations',label:'ปลายทาง'},{id:'vehicle_types',label:'ประเภทรถ'},{id:'need',label:'ต้องการ'},{id:'actions',label:'จัดการ'}],'ไม่มีรายการค้นหา')}</div>
      <div class="tab-pane fade" id="history-pane" role="tabpanel">${tableCard('history','ประวัติงานใน DB','ค้นหา / filter / sort รายการย้อนหลัง และรับงานแบบยืนยันด้วยมือ','historyTable',[{id:'requestId',label:'Request ID'},{id:'bookingId',label:'Booking ID'},{id:'origin',label:'ต้นทาง'},{id:'destination',label:'ปลายทาง'},{id:'vehicleType',label:'ประเภทรถ'},{id:'standbyDateTime',label:'เวลาสแตนบาย'},{id:'createdAt',label:'บันทึกเมื่อ'},{id:'actions',label:'รับงาน'}],'ไม่พบประวัติงาน', true)}</div>
      <div class="tab-pane fade" id="audit-pane" role="tabpanel">${tableCard('audit','ประวัติการใช้งาน','ค้นหาและกรองกิจกรรมผู้ใช้','auditTable',[{id:'id',label:'ID'},{id:'username',label:'ผู้ทำรายการ'},{id:'action',label:'แอคชัน'},{id:'details',label:'รายละเอียด'},{id:'createdAt',label:'เวลา'}],'ไม่พบประวัติการใช้งาน')}</div>
      <div class="tab-pane fade" id="users-pane" role="tabpanel">${tableCard('users','จัดการผู้ใช้งาน','เพิ่มผู้ใช้ใหม่ เปลี่ยนรหัสผ่าน และกำหนด role','usersTable',[{id:'id',label:'ID'},{id:'username',label:'ชื่อผู้ใช้'},{id:'role',label:'Role'},{id:'createdAt',label:'วันที่สร้าง'},{id:'actions',label:'จัดการ'}],'ไม่พบผู้ใช้งาน')}</div>
      <div class="tab-pane fade" id="settings-pane"><div class="panel mx-auto rounded-[1.75rem] p-5" style="max-width:900px;"><div class="mb-4 flex items-center justify-between gap-3"><h5 class="text-lg font-bold text-white">ตั้งค่าระบบ</h5><button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm font-medium text-white" id="theme-toggle-2" type="button">Theme</button></div><form id="settingsForm">...</form></div></div>
      <div class="tab-pane fade" id="notifications-pane" role="tabpanel"><div class="panel rounded-[1.75rem] p-4"><h5 class="mb-3 text-lg font-bold text-white">Notification preview / test</h5><div class="flex gap-2 flex-wrap"><button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-medium text-white" id="notification-preview-button" type="button">Preview</button><button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-medium text-white" id="notification-test-button" type="button">Send Test</button></div><pre class="mt-3 rounded-2xl bg-white/5 p-4 text-sm text-slate-200" id="notification-preview" aria-live="polite" style="white-space:pre-wrap"></pre></div></div>
      <div class="tab-pane fade" id="reports-pane" role="tabpanel"><div class="panel rounded-[1.75rem] p-4"><h5 class="mb-3 text-lg font-bold text-white">Export รายงาน</h5><div class="flex gap-2 flex-wrap"><button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-medium text-white" type="button" data-report-path="/reports/metrics.csv" data-report-file="spx-metrics.csv">Export metrics</button><button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-medium text-white" type="button" data-report-path="/reports/history.csv" data-report-file="spx-history.csv">Export history</button><button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-medium text-white" type="button" data-report-path="/reports/audit.csv" data-report-file="spx-audit.csv">Export audit</button></div></div></div>
    </div>
  </main>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script src="/assets/dashboard.js"></script>
</body>
</html>`;
}
function tableCard(sectionId: string, title: string, description: string, tableId: string, columns: Array<{ id: string; label: string }>, emptyText: string, hasSearch = false): string {
  const search = hasSearch ? `<div class="filters"><input id="${sectionId}-search" class="grid-search" placeholder="ค้นหา"><input id="${sectionId}-origin" class="grid-filter" placeholder="ต้นทาง"><input id="${sectionId}-destination" class="grid-filter" placeholder="ปลายทาง"><input id="${sectionId}-vehicle" class="grid-filter" placeholder="ประเภทรถ"><button class="grid-filter font-medium text-white" id="${sectionId}-search-button" type="button">ค้นหา</button><button class="grid-filter font-medium text-white" id="${sectionId}-reset-button" type="button">ล้าง</button></div>` : '';
  const cols = columns.map((col, index) => `<label class="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-200"><input type="checkbox" checked data-col-toggle="${sectionId}" data-col-index="${index}" class="accent-cyan-400">${col.label}</label>`).join('');
  const bulk = `<div class="flex flex-wrap items-center gap-2"><select class="grid-select" data-bulk-action="${sectionId}"><option value="">Bulk actions</option><option value="toggle-selected">Toggle selected</option><option value="delete-selected">Delete selected</option></select><button class="pager-btn" type="button" data-bulk-apply="${sectionId}">Apply</button><div class="flex flex-wrap gap-2 max-w-full">${cols}</div></div>`;
  const selectCol = `<th data-sortable="false" class="w-10"><input type="checkbox" data-select-all="${sectionId}" class="accent-cyan-400"></th>`;
  const head = columns.map((col, index) => `<th data-col="${index}" data-sortable="true"><span class="sort-indicator">${col.label}<span class="sort-arrow">↕</span></span></th>`).join('');
  return `<div class="grid-shell rounded-[1.75rem] p-4" data-table-card="${sectionId}"><div class="grid-toolbar"><div><h5 class="text-lg font-bold text-white">${title}</h5><p class="text-sm text-slate-400">${description}</p></div>${sectionId === 'rules' ? '<div id="stats" class="text-sm font-bold"></div>' : search}</div><div class="mb-3 flex flex-wrap gap-3">${bulk}<button class="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm font-medium text-white" type="button" data-column-menu-toggle="${sectionId}">Columns</button></div><div class="hidden mb-3 flex flex-wrap gap-2" data-column-menu="${sectionId}">${cols}</div><div class="overflow-auto"><table id="${tableId}" class="grid-table"><thead><tr>${selectCol}${head}</tr></thead><tbody></tbody></table></div><div class="grid-empty hidden" data-empty-state="${sectionId}">${emptyText}</div><div class="mt-4 flex items-center justify-between gap-3 border-t border-white/10 pt-4"><div class="text-sm text-slate-400" data-page-info="${sectionId}"></div><div class="flex items-center gap-2"><select class="grid-select" data-page-size="${sectionId}"><option>10</option><option>25</option><option>50</option></select><button class="pager-btn" data-page-prev="${sectionId}">Prev</button><button class="pager-btn" data-page-next="${sectionId}">Next</button></div></div></div>`;
}
