/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LineImageExtractionsRouteImport } from './routes/line-image-extractions'
import { Route as LineBotRouteImport } from './routes/line-bot'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AutoAcceptHistoryRouteImport } from './routes/auto-accept-history'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsLineBotRouteImport } from './routes/settings.line-bot'
import { Route as SettingsApiRouteImport } from './routes/settings.api'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LineImageExtractionsRoute = LineImageExtractionsRouteImport.update({
  id: '/line-image-extractions',
  path: '/line-image-extractions',
  getParentRoute: () => rootRouteImport,
} as any)
const LineBotRoute = LineBotRouteImport.update({
  id: '/line-bot',
  path: '/line-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoAcceptHistoryRoute = AutoAcceptHistoryRouteImport.update({
  id: '/auto-accept-history',
  path: '/auto-accept-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLineBotRoute = SettingsLineBotRouteImport.update({
  id: '/line-bot',
  path: '/line-bot',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiRoute = SettingsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auto-accept-history': typeof AutoAcceptHistoryRoute
  '/history': typeof HistoryRoute
  '/line-bot': typeof LineBotRoute
  '/line-image-extractions': typeof LineImageExtractionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/settings/api': typeof SettingsApiRoute
  '/settings/line-bot': typeof SettingsLineBotRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auto-accept-history': typeof AutoAcceptHistoryRoute
  '/history': typeof HistoryRoute
  '/line-bot': typeof LineBotRoute
  '/line-image-extractions': typeof LineImageExtractionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/settings/api': typeof SettingsApiRoute
  '/settings/line-bot': typeof SettingsLineBotRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auto-accept-history': typeof AutoAcceptHistoryRoute
  '/history': typeof HistoryRoute
  '/line-bot': typeof LineBotRoute
  '/line-image-extractions': typeof LineImageExtractionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/settings/api': typeof SettingsApiRoute
  '/settings/line-bot': typeof SettingsLineBotRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auto-accept-history'
    | '/history'
    | '/line-bot'
    | '/line-image-extractions'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/teams'
    | '/users'
    | '/settings/api'
    | '/settings/line-bot'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auto-accept-history'
    | '/history'
    | '/line-bot'
    | '/line-image-extractions'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/teams'
    | '/users'
    | '/settings/api'
    | '/settings/line-bot'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auto-accept-history'
    | '/history'
    | '/line-bot'
    | '/line-image-extractions'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/teams'
    | '/users'
    | '/settings/api'
    | '/settings/line-bot'
    | '/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AutoAcceptHistoryRoute: typeof AutoAcceptHistoryRoute
  HistoryRoute: typeof HistoryRoute
  LineBotRoute: typeof LineBotRoute
  LineImageExtractionsRoute: typeof LineImageExtractionsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-image-extractions': {
      id: '/line-image-extractions'
      path: '/line-image-extractions'
      fullPath: '/line-image-extractions'
      preLoaderRoute: typeof LineImageExtractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-bot': {
      id: '/line-bot'
      path: '/line-bot'
      fullPath: '/line-bot'
      preLoaderRoute: typeof LineBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-accept-history': {
      id: '/auto-accept-history'
      path: '/auto-accept-history'
      fullPath: '/auto-accept-history'
      preLoaderRoute: typeof AutoAcceptHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/line-bot': {
      id: '/settings/line-bot'
      path: '/line-bot'
      fullPath: '/settings/line-bot'
      preLoaderRoute: typeof SettingsLineBotRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api': {
      id: '/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof SettingsApiRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsApiRoute: typeof SettingsApiRoute
  SettingsLineBotRoute: typeof SettingsLineBotRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiRoute: SettingsApiRoute,
  SettingsLineBotRoute: SettingsLineBotRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AutoAcceptHistoryRoute: AutoAcceptHistoryRoute,
  HistoryRoute: HistoryRoute,
  LineBotRoute: LineBotRoute,
  LineImageExtractionsRoute: LineImageExtractionsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TeamsRoute: TeamsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
